[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "mypy>=1.15.0",
    "ruff>=0.11.2",
    "uvicorn>=0.34.0",
]
